apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    project: roboshop
    tier: web    
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: web
      project: roboshop
      tier: web    
  template:
    metadata:
      labels:
        app: web
        project: roboshop
        tier: web    
    spec:
      containers:
      - name: web
        image: ramana11k/web:v1
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
    project: roboshop
    tier: web
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port